### ISSUE TITLE
`repr(u*), repr(i*)` explanation is misleading

### ISSUE THREAD

**Issue by ExoticMatter** [rust-lang/nomicon#151]
> Adding an explicit `repr` to an enum suppresses the null-pointer optimization.

This is no longer guaranteed. As long as the enum does not contain both a `MIN` variant and a `MAX` variant, it can still be optimized.

```rust
#[allow(dead_code)]

fn main() {
    use std::mem::size_of;
    use std::i8;
    
    enum RustEnum {
        A,
        B,
    }

    #[repr(i8)]
    enum I8WithoutMin {
        A = i8::MIN + 1,
        B = i8::MAX,
    }

    #[repr(i8)]
    enum I8WithoutMax {
        A = i8::MIN,
        B = i8::MAX - 1,
    }

    #[repr(i8)]
    enum I8WithAll {
        A = i8::MIN,
        B = i8::MAX,
    }

    println!("Size of Option<RustEnum>: {}", size_of::<Option<RustEnum>>());
    println!("Size of Option<I8WithoutMin>: {}", size_of::<Option<I8WithoutMin>>());
    println!("Size of Option<I8WithoutMax>: {}", size_of::<Option<I8WithoutMax>>());
    println!("Size of Option<I8WithAll>: {}", size_of::<Option<I8WithAll>>());
}
```
Output:
```
Size of Option<RustEnum>: 1
Size of Option<I8WithoutMin>: 1
Size of Option<I8WithoutMax>: 1
Size of Option<I8WithAll>: 2
```

**Comment by Gankro** [comment]
There's a misunderstanding here, which means I need to improve the wording. What this is trying to express is that if you write

```rust
#[repr(u8)] 
enum MyOption<T> {
  Some(T), None,
}
```

Then `MyOption<&T>` will not have the null-pointer optimization applied. We still freely assume that the tag of a `repr(int)`-union is valid, and in fact we also assume that the contents are valid. We just don't pack the tag into the contents because we want programmers to be able to access the tag directly, and also didn't want to specify how to acquire packed tag.
