### ISSUE TITLE
Missing explanation of 'Bivariant' in 'Subtyping and Variance' section

### ISSUE THREAD

**Issue by JOE1994** [rust-lang/nomicon#199]
Enum `rustc::ty::Variance` contains 4 variants as below.
```rust
pub enum Variance {
    Covariant,
    Invariant,
    Contravariant,
    Bivariant,
}
```

The current version of the **Subtyping and Variance** section only explains the first 3 variants of the enum `Variance` as below.

> A type constructor F's variance is how the subtyping of its inputs affects the subtyping of its outputs. **There are three kinds of variance in Rust.** Given two types Sub and Super, where Sub is a subtype of Super: 

I found articles that briefly explain the concept of `Bivariant` that could be of reference.
* [*Variance of type and lifetime parameters*](https://github.com/rust-lang/rustc-guide/blob/master/src/variance.md#trait-variance-and-vtable-resolution) from `rustc-guide`
* [*Variance in Rust*](https://medium.com/@kennytm/variance-in-rust-964134dd5b3e) by @kennytm
* [*Variance in Rust: An intuitive explanation*](https://ehsanmkermani.com/2019/03/16/variance-in-rust-an-intuitive-explanation/) by @ehsanmok

**Comment by Gankra** [comment]
Bivariance does not exist as an end-user concept. Or at least, it's easily understood otherwise, and is just used as a thing to make things "just work" in the compiler.

In the Rustonomicon we talk about a type being variant *with respect to* a type parameter. For a type which has no relationship to a type parameter (such as an `i32` wrt some `<T>` that's in scope), you can take two stances:

1. Ignore that type, because it has no effect
2. The type is bivariant wrt `T`... which just means it has no effect

The rustonomicon silently takes position (1) because it would be a distraction to discuss, while the compiler takes position (2) because it makes the algorithm easier to express technically (a type's variance is the lower bound of all its fields' variances, computable with a simple fold).

Either way the result is the same. It's just whether you want to represent something as `Option<3CaseEnum>` or `4CaseEnum`.

**Comment by Gankra** [comment]
Just to be a bit more clear: the reason I say it's a distraction to discuss is because it's a compiler error to create a type that "would" be bivariant wrt one of its type parameters. Hence why you sometimes need to add a `PhantomData<T>` to a struct to "pick" one of the other variances.

**Comment by Gankra** [comment]
Additional Note For History Lawyers: user-defined types which were bivariant wrt their type parameters *was* supported pre-rust-1.0. It was a huge footgun so we removed it. I have no interest in discussing pre-1.0 Rust in the Rustonomicon, as literally every feature you could imagine was at one point part of Rust 0.x.
