### ISSUE TITLE
How can Ord have a safe non-total implementation?

### ISSUE THREAD

**Issue by hahohihu** [rust-lang/nomicon#247]
"How Safe and Unsafe Interact" says:
> the Unsafe code in BTreeMap must be written to be robust against Ord implementations which aren't actually total — even though that's the whole point of requiring Ord

Other than panics or process::exit, I'm unsure how a safe Ord implementation could be non-total. `cmp` would have to return something that isn't an Ordering, which seems like undefined behavior. 

I also haven't been able to find anything dealing with this in the BTreeMap code. Sorry if this is just me being a novice, or if this is outside the scope of the nomicon.

**Comment by Havvy** [comment]
It's not undefined behavior. It's logically incorrect and will lead to incorrect results in code that assumes all Ord implementations are total. It's a logical bug in the code that does this. And it's entirely possible to make safe code that does violate the contract of Ord. As such, unsafe code cannot rely on Ord implementations being correct to maintain soundness.

You don't see anything dealing with this in BTreeMap explicitly because, like a lot of dealing with unsafe things, the details are hidden in implicit structure.

**Comment by hahohihu** [comment]
Ah sorry, I misinterpreted what "total ordering" meant. I interpreted a "partially-ordered type" to be the same as PartialOrd - i.e. the cmp function is undefined on some values, but double-checking the definition of 'total order' in Ord, it just means some a, b, and c aren't transitive. Thanks for the clarification!
